### ISSUE TITLE
Refactor navbar so it's not included into every single page

### ISSUE THREAD

**Issue by giancorzo** [Laboratoria/capitan-www#10]
Currently the navbar is included in the main app.js container so we need to change that so the navbar is only included in the private routes and not in the login page or other public pages.

**Comment by giancorzo** [comment]
I refactored the app container so the navbar is only included in the page that need to include it and in all of the privateRouters.

**Comment by lupomontero** [comment]
@giancorzo: where can I see the refactoring?

**Comment by giancorzo** [comment]
Everything is merge into master... perhaps we should define some sort of flow before merging into master.

**Comment by lupomontero** [comment]
@giancorzo ie: pull request? ;-)
